[package]
name = "lcov-util"
version = "0.1.0"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
description = "Utility commands to operate and analyze LCOV trace file at blazingly fast."
readme = "README.md"
keywords = ["lcov", "coverage", "gcov"]
categories = ["command-line-utilities", "parsing"]
license = "MIT/Apache-2.0"
repository = "https://github.com/gifnksm/lcov/"

[dependencies]
lcov = { version = "0.2", path = "lcov" }
failure = "0.1"
structopt = "0.2"

[badges]
travis-ci = { repository = "gifnksm/lcov", branch = "master" }

[workspace]
members = ["lcov"]
